data:
  data_folder: data/
  13f_submitters : data/2022q2_form13f/SUBMISSION.tsv
  13_filings : data/13f/sec-edgar-filings/
  name_to_cik : data/name_to_cik.csv
  edgelists : data/edgelist/
  error_csv_path : data/failed_to_load_paths.csv
  industry_url : https://stockmarketmba.com/listofstocksinanindustry.php
  industry_list_path : data/industries/industry_list.csv
  industries : data/industries/
  node_info_path : data/final/node_info.csv
  edgelist_path : data/final/edgelist.csv

parameters:
  similarity_treshold : 0.9
  chunksize : 50
