data:
  data_folder: data/
  13f_submitters : data/2022q2_form13f/OTHERMANAGER.tsv
  13_filings : data/13f/sec-edgar-filings/
  name_to_cik : data/name_to_cik.csv
  edgelists : data/edgelist/
  error_csv_path : data/failed_to_load_paths.csv
  10q_filings : data/10q/sec-edgar-filings/
  no_10q_path : data/companies_wo_10q.csv