data:
  data_folder: data/
  13f_submitters : data/2022q2_form13f/SUBMISSION.tsv
  13_filings : data/13f/sec-edgar-filings/
  edgelists : data/edgelist/
  financials : data/refinitiv/
  error_csv_path : data/failed_to_load_paths.csv
  similarity_path : data/working_files/similarity.csv
  edgelist_temp: data/working_files/edgelist.csv
  node_temp: data/working_files/nodes.csv
  node_path : data/final/nodes.csv
  edgelist_path : data/final/edgelist.csv

parameters:
  similarity_treshold : 0.9
  chunksize : 50
