data:
  data_folder: data/
  13f_submitters : data/2022q2_form13f/SUBMISSION.tsv
  13_filings : data/13f/sec-edgar-filings/
  edgelists : data/edgelist/
  financials : data/refinitiv/
  error_csv_path : data/failed_to_load_paths.csv
  similarity_path : data/working_files/similarity/
  edgelist_temp: data/working_files/edgelist.csv
  node_temp: data/working_files/nodes.csv
  edgelist_full : data/working_files/edgelist_full.csv
  similarity : data/working_files/similarity.csv
  node_path : data/final/nodes.csv
  edgelist_path : data/final/edgelist.csv

parameters:
  similarity_threshold : 0.91
  chunksize : 50

lists:
  wrong_nodes:
    - ubs_americas
    - bnp_paribas_arbitrage_sa
    - dnb_as
    - westpac_banking
    - capital_fund_s_a
    - border_to_coast_pensions_partnership
    - liontrust_investment_partners_llp
    - ubs_oconnor
    - westend_advisors
    - kiwi_wealth_investments_limited_partnership
    - venture_visionary_partners
    - kinneret_advisory
    - adell_harriman_carpenter
    - tower_bridge_advisors
    - fishman_jay_a_mi
    - blue_edge_capital
    - rowland_investment_counselad

  sectors:
    - Consumer Discretionary
    - Communication Services
    - Industrials
    - Health Care
    - Information Technology 
    - Materials
    - Utilities
    - Consumer Staples
    - Energy
    - Real Estate

graph:
  graph_path: "data/graphs/projected.gexf"

outputs:
  descriptive_table : data/outputs/decriptive_table.csv
  sector_analysis : data/outputs/sector_analysis.csv
  simulations : data/outputs/simulations/
  plots : plots/
